const tableHeader = [
  {
    prop:'factoryName',
    label:'工厂名称',
    width:250
  },
  {
    prop:'factoryAddress',
    label:'工厂地址',
    width:450
  },
  {
    prop:'factoryCodeStr',
    label:'工厂编码',
    width:180
  },
  {
    prop:'registerUser',
    label:'联系人',
  },
  {
    prop:'registerMobile',
    label:'手机号码',
  },
  {
    prop:'registerGender',
    label:'性别',
    render(row){
        console.log(row.registerGender)
        return row.registerGender;
    }
  },
  {
    prop:'createTime',
    label:'创建时间',
  },
  {
    prop:'operation',
    label:'操作',
  },
]
export default tableHeader;